## Introduction to Data Science

### Accessing and Manipulating Data in different formats

In [1]:
import os
import sys
import time
import datetime
import numpy as np
import pandas as pd
import pathlib

In [2]:
datapath = pathlib.Path("../datasets/CSVs/")
outputs = pathlib.Path("../outputs/")

## Acessing CSV Files

In [3]:
csvfile = "beatles-diskography.csv"
datafile = datapath / csvfile

#### Using pure Python:

In [4]:
data = []
with open(datafile, "r") as f:
    keys = f.readline().split(',')
    keys = [k.strip() for k in keys]
    for i in range(5):
        values = f.readline().split(',')
        values = [v.strip() for v in values]
        d = dict(zip(keys,values))
        data.append(d)
data[0:2]

[{'BPI Certification': 'Gold',
  'Label': 'Parlophone(UK)',
  'RIAA Certification': 'Platinum',
  'Released': '22 March 1963',
  'Title': 'Please Please Me',
  'UK Chart Position': '1',
  'US Chart Position': '-'},
 {'BPI Certification': 'Platinum',
  'Label': 'Parlophone(UK)',
  'RIAA Certification': 'Gold',
  'Released': '22 November 1963',
  'Title': 'With the Beatles',
  'UK Chart Position': '1',
  'US Chart Position': '-'}]

#### Using CSV module:

https://docs.python.org/3/library/csv.html

In [5]:
import csv

In [6]:
with open(datafile, "r") as f:
    #data2 = csv.reader(f)
    data2 = csv.DictReader(f)
    for row in data2:
        print(row)

OrderedDict([('Title', 'Please Please Me'), ('Released', '22 March 1963'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Gold'), ('RIAA Certification', 'Platinum')])
OrderedDict([('Title', 'With the Beatles'), ('Released', '22 November 1963'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Platinum'), ('RIAA Certification', 'Gold')])
OrderedDict([('Title', 'Beatlemania! With the Beatles'), ('Released', '25 November 1963'), ('Label', 'Capitol(CAN)'), ('UK Chart Position', '-'), ('US Chart Position', '-'), ('BPI Certification', ''), ('RIAA Certification', '')])
OrderedDict([('Title', 'Introducing... The Beatles'), ('Released', '10 January 1964'), ('Label', 'Vee-Jay(US)'), ('UK Chart Position', '-'), ('US Chart Position', '2'), ('BPI Certification', ''), ('RIAA Certification', '')])
OrderedDict([('Title', 'Meet the Beatles!'), ('Released', '20 January 1964'), ('Label', 'Capitol(US)'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '5xPlatinum')])
OrderedDict([('Title', 'Twist and Shout'), ('Released', '3 February 1964'), ('Label', 'Capitol(CAN)'), ('UK Chart Position', '-'), ('US Chart Position', '-'), ('BPI Certification', ''), ('RIAA Certification', '')])
OrderedDict([('Title', "The Beatles' Second Album"), ('Released', '10 April 1964'), ('Label', 'Capitol(US)'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '2xPlatinum')])
OrderedDict([('Title', "The Beatles' Long Tall Sally"), ('Released', '11 May 1964'), ('Label', 'Capitol(CAN)'), ('UK Chart Position', '-'), ('US Chart Position', '-'), ('BPI Certification', ''), ('RIAA Certification', '')])
OrderedDict([('Title', "A Hard Day's Night"), ('Released', '26 June 1964'), ('Label', 'United Artists(US)[C]'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '4xPlatinum')])
OrderedDict([('Title', ''), ('Released', '10 July 1964'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Gold'), ('RIAA Certification', '')])
OrderedDict([('Title', 'Something New'), ('Released', '20 July 1964'), ('Label', 'Capitol(US)'), ('UK Chart Position', '-'), ('US Chart Position', '2'), ('BPI Certification', ''), ('RIAA Certification', 'Platinum')])
OrderedDict([('Title', 'Beatles for Sale'), ('Released', '4 December 1964'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Gold'), ('RIAA Certification', 'Platinum')])
OrderedDict([('Title', "Beatles '65"), ('Released', '15 December 1964'), ('Label', 'Capitol(US)'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '3xPlatinum')])
OrderedDict([('Title', 'Beatles VI'), ('Released', '14 June 1965'), ('Label', 'Parlophone(NZ), Capitol(US)'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', 'Platinum')])
OrderedDict([('Title', 'Help!'), ('Released', '6 August 1965'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Platinum'), ('RIAA Certification', '')])
OrderedDict([('Title', ''), ('Released', '13 August 1965'), ('Label', 'Capitol(US)[C]'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '3xPlatinum')])
OrderedDict([('Title', 'Rubber Soul'), ('Released', '3 December 1965'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Platinum'), ('RIAA Certification', '')])
OrderedDict([('Title', ''), ('Released', '6 December 1965'), ('Label', 'Capitol(US)[C]'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '6xPlatinum')])
OrderedDict([('Title', 'Yesterday and Today'), ('Released', '15 June 1966'), ('Label', 'Capitol(US)'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '2xPlatinum')])
OrderedDict([('Title', 'Revolver'), ('Released', '5 August 1966'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Platinum'), ('RIAA Certification', '')])
OrderedDict([('Title', ''), ('Released', '8 August 1966'), ('Label', 'Capitol(US)[C]'), ('UK Chart Position', '-'), ('US Chart Position', '1'), ('BPI Certification', ''), ('RIAA Certification', '5xPlatinum')])
OrderedDict([('Title', "Sgt. Pepper's Lonely Hearts Club Band"), ('Released', '1 June 1967'), ('Label', 'Parlophone(UK), Capitol(US)'), ('UK Chart Position', '1'), ('US Chart Position', '1'), ('BPI Certification', '3xPlatinum'), ('RIAA Certification', '11xPlatinum')])
OrderedDict([('Title', 'Magical Mystery Tour'), ('Released', '27 November 1967'), ('Label', 'Parlophone(UK), Capitol(US)'), ('UK Chart Position', '31[D]'), ('US Chart Position', '1'), ('BPI Certification', 'Platinum'), ('RIAA Certification', '6xPlatinum')])
OrderedDict([('Title', 'The Beatles'), ('Released', '22 November 1968'), ('Label', 'Apple(UK), Capitol(US)'), ('UK Chart Position', '1'), ('US Chart Position', '1'), ('BPI Certification', 'Platinum'), ('RIAA Certification', '19xPlatinum')])
OrderedDict([('Title', 'Yellow Submarine'), ('Released', '13 January 1969'), ('Label', 'Apple(UK), Capitol(US)'), ('UK Chart Position', '3'), ('US Chart Position', '2'), ('BPI Certification', 'Silver'), ('RIAA Certification', 'Platinum')])
OrderedDict([('Title', 'Abbey Road'), ('Released', '26 September 1969'), ('Label', 'Apple(UK), Capitol(US)'), ('UK Chart Position', '1'), ('US Chart Position', '1'), ('BPI Certification', '2xPlatinum'), ('RIAA Certification', '12xPlatinum')])
OrderedDict([('Title', 'Let It Be'), ('Released', '8 May 1970'), ('Label', 'Apple(UK),United Artists(US)'), ('UK Chart Position', '1'), ('US Chart Position', '1'), ('BPI Certification', 'Gold'), ('RIAA Certification', '4xPlatinum')])

#### Using Pandas:

In [7]:
df_csv = pd.read_csv(datafile)
df_csv.head()
#df_csv.info()

,Title,Released,Label,UK Chart Position,US Chart Position,BPI Certification,RIAA Certification
0,Please Please Me,22 March 1963,Parlophone(UK),1,-,Gold,Platinum
1,With the Beatles,22 November 1963,Parlophone(UK),1,-,Platinum,Gold
2,Beatlemania! With the Beatles,25 November 1963,Capitol(CAN),-,-,NaN,NaN
3,Introducing... The Beatles,10 January 1964,Vee-Jay(US),-,2,NaN,NaN
4,Meet the Beatles!,20 January 1964,Capitol(US),-,1,NaN,5xPlatinum

## Manipulating Zip Files

https://docs.python.org/3/library/zipfile.html

In [8]:
from zipfile import ZipFile

In [9]:
zipfile = "2013_ERCOT_Hourly_Load_Data"

In [12]:
with ZipFile('{0}.zip'.format(datapath / zipfile), 'r') as myzip:
    with myzip.open('2013_ERCOT_Hourly_Load_Data.xls') as myfile:
        pd_excel = pd.read_excel(myfile)
pd_excel.head()

,Hour_End,COAST,EAST,FAR_WEST,NORTH,NORTH_C,SOUTHERN,SOUTH_C,WEST,ERCOT
0,2013-01-01 01:00:00,7606.263544,1073.892438,1411.750567,784.978166,10369.094390,2206.675077,4368.490945,882.931901,28704.077028
1,2013-01-01 02:00:00,7388.082714,1035.021938,1403.472287,776.307387,10152.358518,2159.733208,4233.587967,872.404750,28020.968769
2,2013-01-01 03:00:00,7178.867878,1036.088697,1395.053150,768.125748,9988.051418,2065.114706,4082.862860,868.853938,27383.018395
3,2013-01-01 04:00:00,7038.822581,1032.648841,1395.508820,770.937969,9946.658655,1990.903699,4010.489608,865.701201,27051.671374
4,2013-01-01 05:00:00,6990.857940,1042.823044,1401.216842,779.089313,10096.664190,1954.807585,4038.655997,879.924249,27184.039160

## Acessing and Writing Excel Files

https://pypi.python.org/pypi/xlrd  
https://pypi.python.org/pypi/xlwt  
https://github.com/python-excel/tutorial/blob/master/python-excel.pdf

#### Accessing a workbook

In [13]:
import xlrd

In [14]:
datafile = "2013_ERCOT_Hourly_Load_Data.xls"

In [16]:
with ZipFile('{0}.zip'.format(datapath / zipfile), 'r') as myzip:
    myzip.extractall(datapath)

In [17]:
workbook = xlrd.open_workbook(datapath / datafile)
sheet = workbook.sheet_by_index(0)

In [18]:
sheet_data = [[sheet.cell_value(r, col) for col in range(sheet.ncols)] for r in range(sheet.nrows)]
sheet_data[:2]

[['Hour_End',
  'COAST',
  'EAST',
  'FAR_WEST',
  'NORTH',
  'NORTH_C',
  'SOUTHERN',
  'SOUTH_C',
  'WEST',
  'ERCOT'],
 [41275.041666666664,
  7606.263544000012,
  1073.892438,
  1411.7505669999982,
  784.9781659999992,
  10369.094390000051,
  2206.6750770000012,
  4368.490945000006,
  882.9319009999975,
  28704.077028000065]]

In [19]:
print("Number of rows in the sheet:"),
print(sheet.nrows)

Number of rows in the sheet:
7296

In [20]:
print("Type of data in cell (row 3, col 2):"), 
print(sheet.cell_type(3, 2))

Type of data in cell (row 3, col 2):
2

In [21]:
print("Value in cell (row 3, col 2):", )
print(sheet.cell_value(3, 2))

Value in cell (row 3, col 2):
1036.0886969999988

In [22]:
print("Get a slice of values in column 3, from rows 1-3:",)
print(sheet.col_values(3, start_rowx=1, end_rowx=4))

Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

In [23]:
coast = sheet.col_values(1, start_rowx=1)
data3 = {}    
data3['maxvalue'] = max(coast)
data3['minvalue'] = min(coast)
data3['avgcoast'] = np.mean(coast)

rowmax = coast.index(max(coast))+1
rowmin = coast.index(min(coast))+1

data3['maxtime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmax,0), 0)
data3['mintime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmin,0), 0)

In [24]:
data3

{'avgcoast': 10976.933460679784,
 'maxtime': (2013, 8, 13, 17, 0, 0),
 'maxvalue': 18779.025510000003,
 'mintime': (2013, 2, 3, 4, 0, 0),
 'minvalue': 6602.113898999982}

#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html

In [25]:
pd_excel = pd.read_excel(datapath / datafile)
pd_excel.head()

,Hour_End,COAST,EAST,FAR_WEST,NORTH,NORTH_C,SOUTHERN,SOUTH_C,WEST,ERCOT
0,2013-01-01 01:00:00,7606.263544,1073.892438,1411.750567,784.978166,10369.094390,2206.675077,4368.490945,882.931901,28704.077028
1,2013-01-01 02:00:00,7388.082714,1035.021938,1403.472287,776.307387,10152.358518,2159.733208,4233.587967,872.404750,28020.968769
2,2013-01-01 03:00:00,7178.867878,1036.088697,1395.053150,768.125748,9988.051418,2065.114706,4082.862860,868.853938,27383.018395
3,2013-01-01 04:00:00,7038.822581,1032.648841,1395.508820,770.937969,9946.658655,1990.903699,4010.489608,865.701201,27051.671374
4,2013-01-01 05:00:00,6990.857940,1042.823044,1401.216842,779.089313,10096.664190,1954.807585,4038.655997,879.924249,27184.039160

#### Reading and Writing a Workbook

In [27]:
import xlwt

In [28]:
style0 = xlwt.easyxf('font: name Times New Roman, color-index red, bold on', num_format_str='#,##0.00')
style1 = xlwt.easyxf(num_format_str='D-MMM-YY')

In [30]:
workbook = xlwt.Workbook()
workbook_name = 'my_workbook.xls'

worksheet1 = workbook.add_sheet('my_first_sheet')
worksheet1.write(0, 0, 'Column 1 title', style0)
worksheet1.write(0, 1, 'Column 2 title', style0)

worksheet2 = workbook.add_sheet('my_second_sheet')
worksheet2.write(0, 0, 'Itens')
worksheet2.write(0, 1, 'Price')
worksheet2.write(1, 0, 'Rice')
worksheet2.write(1, 1, 100)
worksheet2.write(2, 0, 'Beans')
worksheet2.write(2, 1, 200)
worksheet2.write(3, 0, 'Pasta')
worksheet2.write(3, 1, 500)
worksheet2.write(5, 0, 'Total')

worksheet2.write(5, 1, xlwt.Formula("B2+B3+B4"))


workbook.save(outputs / workbook_name)

## Accessing HTML

https://docs.python.org/3/library/urllib.html  
http://www.crummy.com/software/BeautifulSoup/  
http://docs.python-requests.org/en/latest/  
http://lxml.de/  
https://docs.python.org/3/library/getpass.html

In [31]:
import urllib
from bs4 import BeautifulSoup as bs
import requests
import lxml.html
import getpass

In [33]:
url = "http://oglobo.globo.com"
html_txt = urllib.request.urlopen(url).read()
soup = bs(html_txt, "html.parser")
 
[line.get('href') for line in soup.find_all('a')][0:10]

['/',
 'http://memoria.oglobo.globo.com',
 'http://acervo.oglobo.globo.com',
 'ela/',
 'http://kogut.oglobo.globo.com',
 'rioshow/',
 'https://extra.globo.com',
 'http://classificados.globo.com',
 'http://clubeoglobo.com.br',
 'http://www.centraldoassinante.oglobo.com.br']

#### Another approach: lxml instead of beautiful soup
http://lxml.de/tutorial.html

In [34]:
url = "http://www.hotashtanga.com/p/letoltesek-downloads.html"
html_txt = urllib.request.urlopen(url).read()
dom =  lxml.html.fromstring(html_txt)
    
[line for line in dom.xpath('//a/@href')][0:10]

['http://www.hotashtanga.com/',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5eGVjNDFaQmFhZXM',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5dnJEamZaWmpieGs',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5eGMzX0U4ZVFNNjA',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5WlZxM1BZdGcyNE0',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5ZzVLcUV4ZTItcm8',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5RmxId2RzYlA2ek0',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5ZU9Ta0NyUkMtWnc',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5SEM0UXBHVWlUeWc',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5aUU5TEZIYURCaUE']

#### Using Requests, for more complex tasks  

http://docs.python-requests.org/en/master/user/quickstart/  
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

In [36]:
p = getpass.getpass()
r = requests.get('https://api.github.com/user', auth=('rsouza', p))
r.status_code

200

In [38]:
r.headers['content-type']

'application/json; charset=utf-8'

In [39]:
r.encoding

'utf-8'

In [40]:
r.text

'{"login":"rsouza","id":604914,"avatar_url":"https://avatars0.githubusercontent.com/u/604914?v=4","gravatar_id":"","url":"https://api.github.com/users/rsouza","html_url":"https://github.com/rsouza","followers_url":"https://api.github.com/users/rsouza/followers","following_url":"https://api.github.com/users/rsouza/following{/other_user}","gists_url":"https://api.github.com/users/rsouza/gists{/gist_id}","starred_url":"https://api.github.com/users/rsouza/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rsouza/subscriptions","organizations_url":"https://api.github.com/users/rsouza/orgs","repos_url":"https://api.github.com/users/rsouza/repos","events_url":"https://api.github.com/users/rsouza/events{/privacy}","received_events_url":"https://api.github.com/users/rsouza/received_events","type":"User","site_admin":false,"name":"Renato Rocha Souza","company":"FGV","blog":"emap.fgv.br","location":"Rio de Janeiro","email":"rsouza.fgv@gmail.com","hireable":null,"bio":"https://www.linkedin.com/in/renato-rocha-souza-157153","public_repos":17,"public_gists":2,"followers":62,"following":6,"created_at":"2011-02-07T15:46:45Z","updated_at":"2018-03-01T11:05:01Z","private_gists":0,"total_private_repos":1,"owned_private_repos":0,"disk_usage":818572,"collaborators":0,"two_factor_authentication":false,"plan":{"name":"free","space":976562499,"collaborators":0,"private_repos":0}}'

In [41]:
r.json()

{'avatar_url': 'https://avatars0.githubusercontent.com/u/604914?v=4',
 'bio': 'https://www.linkedin.com/in/renato-rocha-souza-157153',
 'blog': 'emap.fgv.br',
 'collaborators': 0,
 'company': 'FGV',
 'created_at': '2011-02-07T15:46:45Z',
 'disk_usage': 818572,
 'email': 'rsouza.fgv@gmail.com',
 'events_url': 'https://api.github.com/users/rsouza/events{/privacy}',
 'followers': 62,
 'followers_url': 'https://api.github.com/users/rsouza/followers',
 'following': 6,
 'following_url': 'https://api.github.com/users/rsouza/following{/other_user}',
 'gists_url': 'https://api.github.com/users/rsouza/gists{/gist_id}',
 'gravatar_id': '',
 'hireable': None,
 'html_url': 'https://github.com/rsouza',
 'id': 604914,
 'location': 'Rio de Janeiro',
 'login': 'rsouza',
 'name': 'Renato Rocha Souza',
 'organizations_url': 'https://api.github.com/users/rsouza/orgs',
 'owned_private_repos': 0,
 'plan': {'collaborators': 0,
  'name': 'free',
  'private_repos': 0,
  'space': 976562499},
 'private_gists': 0,
 'public_gists': 2,
 'public_repos': 17,
 'received_events_url': 'https://api.github.com/users/rsouza/received_events',
 'repos_url': 'https://api.github.com/users/rsouza/repos',
 'site_admin': False,
 'starred_url': 'https://api.github.com/users/rsouza/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/rsouza/subscriptions',
 'total_private_repos': 1,
 'two_factor_authentication': False,
 'type': 'User',
 'updated_at': '2018-03-01T11:05:01Z',
 'url': 'https://api.github.com/users/rsouza'}

## Accessing JSON

http://json.org/  
https://docs.python.org/3/library/json.html  
https://docs.python.org/3/library/urllib.html

In [48]:
import json

In [49]:
base_url = "http://musicbrainz.org/ws/2/"
artist_url =  urllib.parse.urljoin(base_url, 'artist/')
query_type = {"simple": {},
              "atr": {"inc": "aliases+tags+ratings"},
              "aliases": {"inc": "aliases"},
              "releases": {"inc": "releases"}}

In [50]:
def query_site(url, params, uid="", fmt="json"):
    params["fmt"] = fmt
    r = requests.get(url + uid, params=params)
    print("requesting", r.url)

    if r.status_code == requests.codes.ok:
        return r.json()
    else:
        r.raise_for_status()

In [51]:
def query_by_name(url, params, name):
    params["query"] = "artist:" + name
    return query_site(url, params)

In [52]:
def pretty_print(data, indent=4):
    if type(data) == dict:
        print(json.dumps(data, indent=indent, sort_keys=True))
    else:
        print(data)

In [53]:
results = query_by_name(artist_url, query_type["simple"], "Nirvana")
pretty_print(results)

requesting http://musicbrainz.org/ws/2/artist/?query=artist%3ANirvana&fmt=json
{
    "artists": [
        {
            "area": {
                "id": "6a264f94-6ff1-30b1-9a81-41f7bfabd616",
                "name": "Finland",
                "sort-name": "Finland"
            },
            "country": "FI",
            "disambiguation": "Early 1980's Finnish punk band",
            "id": "85af0709-95db-4fbc-801a-120e9f4766d0",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana",
            "score": "100",
            "sort-name": "Nirvana",
            "tags": [
                {
                    "count": 1,
                    "name": "punk"
                },
                {
                    "count": 1,
                    "name": "finland"
                }
            ],
            "type": "Group"
        },
        {
            "disambiguation": "founded in 1987 by a Michael Jackson double/imitator",
            "id": "3aa878c0-224b-41e5-abd1-63be359d2bca",
            "life-span": {
                "begin": "1987",
                "ended": null
            },
            "name": "Nirvana",
            "score": "100",
            "sort-name": "Nirvana"
        },
        {
            "disambiguation": "French band from Martigues, activ during the 70s.",
            "id": "c49d69dc-e008-47cf-b5ff-160fafb1fe1f",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana",
            "score": "100",
            "sort-name": "Nirvana"
        },
        {
            "area": {
                "id": "8a754a16-0027-3a29-b6d7-2b40ea0481ed",
                "name": "United Kingdom",
                "sort-name": "United Kingdom"
            },
            "begin-area": {
                "id": "f03d09b3-39dc-4083-afd6-159e3f0d462f",
                "name": "London",
                "sort-name": "London"
            },
            "country": "GB",
            "disambiguation": "60s band from the UK",
            "id": "9282c8b4-ca0b-4c6b-b7e3-4f7762dfc4d6",
            "life-span": {
                "begin": "1967",
                "ended": null
            },
            "name": "Nirvana",
            "score": "100",
            "sort-name": "Nirvana",
            "tags": [
                {
                    "count": 1,
                    "name": "rock"
                },
                {
                    "count": 1,
                    "name": "pop"
                },
                {
                    "count": 1,
                    "name": "progressive rock"
                },
                {
                    "count": 1,
                    "name": "orchestral"
                },
                {
                    "count": 1,
                    "name": "british"
                },
                {
                    "count": 1,
                    "name": "power pop"
                },
                {
                    "count": 1,
                    "name": "psychedelic rock"
                },
                {
                    "count": 1,
                    "name": "soft rock"
                },
                {
                    "count": 1,
                    "name": "symphonic rock"
                },
                {
                    "count": 1,
                    "name": "english"
                }
            ],
            "type": "Group"
        },
        {
            "aliases": [
                {
                    "begin-date": null,
                    "end-date": null,
                    "locale": null,
                    "name": "Nirvana US",
                    "primary": null,
                    "sort-name": "Nirvana US",
                    "type": null
                }
            ],
            "area": {
                "id": "489ce91b-6658-3307-9877-795b68554c98",
                "name": "United States",
                "sort-name": "United States"
            },
            "begin-area": {
                "id": "a640b45c-c173-49b1-8030-973603e895b5",
                "name": "Aberdeen",
                "sort-name": "Aberdeen"
            },
            "country": "US",
            "disambiguation": "90s US grunge band",
            "id": "5b11f4ce-a62d-471e-81fc-a69a8278c7da",
            "life-span": {
                "begin": "1988-01",
                "end": "1994-04-05",
                "ended": true
            },
            "name": "Nirvana",
            "score": "100",
            "sort-name": "Nirvana",
            "tags": [
                {
                    "count": 9,
                    "name": "rock"
                },
                {
                    "count": 4,
                    "name": "alternative rock"
                },
                {
                    "count": 1,
                    "name": "90s"
                },
                {
                    "count": 1,
                    "name": "punk"
                },
                {
                    "count": 5,
                    "name": "american"
                },
                {
                    "count": 1,
                    "name": "seattle"
                },
                {
                    "count": 14,
                    "name": "grunge"
                },
                {
                    "count": 0,
                    "name": "band"
                },
                {
                    "count": 1,
                    "name": "usa"
                },
                {
                    "count": 0,
                    "name": "alternative"
                },
                {
                    "count": 0,
                    "name": "am\u00e9ricain"
                },
                {
                    "count": 0,
                    "name": "legendary"
                },
                {
                    "count": 1,
                    "name": "acoustic rock"
                },
                {
                    "count": 1,
                    "name": "noise rock"
                },
                {
                    "count": 0,
                    "name": "90"
                },
                {
                    "count": 0,
                    "name": "northwest"
                },
                {
                    "count": 0,
                    "name": "rock and indie"
                },
                {
                    "count": 0,
                    "name": "united states"
                },
                {
                    "count": 0,
                    "name": "nirvana"
                },
                {
                    "count": 0,
                    "name": "kurt cobain"
                }
            ],
            "type": "Group"
        },
        {
            "area": {
                "id": "489ce91b-6658-3307-9877-795b68554c98",
                "name": "United States",
                "sort-name": "United States"
            },
            "country": "US",
            "id": "c3a64a25-251b-4d03-afba-1471440245b8",
            "life-span": {
                "begin": "2009",
                "ended": null
            },
            "name": "Approaching Nirvana",
            "score": "62",
            "sort-name": "Approaching Nirvana",
            "type": "Group"
        },
        {
            "id": "b305320e-c158-43f4-b5be-4450e2f99a32",
            "life-span": {
                "ended": null
            },
            "name": "El Nirvana",
            "score": "62",
            "sort-name": "Nirvana, El"
        },
        {
            "aliases": [
                {
                    "begin-date": null,
                    "end-date": null,
                    "locale": null,
                    "name": "Nirvana",
                    "primary": null,
                    "sort-name": "Nirvana",
                    "type": null
                },
                {
                    "begin-date": null,
                    "end-date": null,
                    "locale": null,
                    "name": "Prophet 2002",
                    "primary": null,
                    "sort-name": "Prophet 2002",
                    "type": null
                }
            ],
            "area": {
                "id": "23d10872-f5ae-3f0c-bf55-332788a16ecb",
                "name": "Sweden",
                "sort-name": "Sweden"
            },
            "country": "SE",
            "disambiguation": "Swedish death metal band",
            "id": "f2dfdff9-3862-4be0-bf85-9c833fa3059e",
            "life-span": {
                "begin": "1988",
                "ended": null
            },
            "name": "Nirvana 2002",
            "score": "62",
            "sort-name": "Nirvana 2002",
            "type": "Group"
        },
        {
            "id": "329c04ae-3b73-4ca3-996f-75608ab1befb",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana Singh",
            "score": "62",
            "sort-name": "Singh, Nirvana",
            "type": "Person"
        },
        {
            "area": {
                "id": "489ce91b-6658-3307-9877-795b68554c98",
                "name": "United States",
                "sort-name": "United States"
            },
            "country": "US",
            "gender": "female",
            "id": "206419e0-3a7a-49ce-8437-4e757767d02b",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana Savoury",
            "score": "62",
            "sort-name": "Savoury, Nirvana",
            "type": "Person"
        },
        {
            "id": "86f9ae24-ba2a-4d55-9275-0b89b85f6e3a",
            "life-span": {
                "ended": null
            },
            "name": "Weed Nirvana",
            "score": "62",
            "sort-name": "Weed Nirvana"
        },
        {
            "id": "f58febd3-18de-4371-8d95-4a68d4f79456",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana Kelly",
            "score": "62",
            "sort-name": "Kelly, Nirvana",
            "type": "Person"
        },
        {
            "area": {
                "id": "07607044-8140-47ba-bb24-7129babe586b",
                "name": "West Midlands",
                "sort-name": "West Midlands"
            },
            "id": "8f32371e-4bac-4090-ba13-2c1cd1aeab0d",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana UK",
            "score": "62",
            "sort-name": "Nirvana UK",
            "type": "Group"
        },
        {
            "begin-area": {
                "id": "ef1b7cc0-cd26-36f4-8ea0-04d9623786c7",
                "name": "Netherlands",
                "sort-name": "Netherlands"
            },
            "id": "da77e424-c473-481e-a2ae-5d966b2ee0b6",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana Undercover",
            "score": "62",
            "sort-name": "Nirvana Undercover",
            "type": "Group"
        },
        {
            "area": {
                "id": "c621114d-73cc-4832-8afe-f13dc261e5af",
                "name": "Gatineau",
                "sort-name": "Gatineau"
            },
            "begin-area": {
                "id": "c621114d-73cc-4832-8afe-f13dc261e5af",
                "name": "Gatineau",
                "sort-name": "Gatineau"
            },
            "id": "02c4e6bb-7b7a-4686-8c23-df01bfd42b0e",
            "life-span": {
                "begin": "2012-04-05",
                "ended": null
            },
            "name": "Sappy Nirvana Tribute",
            "score": "50",
            "sort-name": "Sappy Nirvana Tribute",
            "type": "Group"
        },
        {
            "area": {
                "id": "e8ad73e9-9e7f-41c4-a395-6e29260ff1df",
                "name": "Graz",
                "sort-name": "Graz"
            },
            "begin-area": {
                "id": "e8ad73e9-9e7f-41c4-a395-6e29260ff1df",
                "name": "Graz",
                "sort-name": "Graz"
            },
            "disambiguation": "Nirvana-Coverband",
            "id": "46d8dae4-abec-438b-9c62-a3dbb2aaa1b7",
            "life-span": {
                "begin": "2000",
                "ended": null
            },
            "name": "Nirvana Teen Spirit",
            "score": "50",
            "sort-name": "Nirvana Teen Spirit",
            "type": "Group"
        },
        {
            "id": "bb94730d-22c2-422d-a0a7-fe16a5b3e429",
            "life-span": {
                "ended": null
            },
            "name": "The Attainment of Nirvana",
            "score": "50",
            "sort-name": "Attainment of Nirvana, The",
            "type": "Group"
        },
        {
            "area": {
                "id": "c920948b-83e3-40b7-8fe9-9ab5abaac55b",
                "name": "Houston",
                "sort-name": "Houston"
            },
            "begin-area": {
                "id": "c920948b-83e3-40b7-8fe9-9ab5abaac55b",
                "name": "Houston",
                "sort-name": "Houston"
            },
            "disambiguation": "Nirvana Cover Band",
            "id": "45eacd92-6857-4faa-9283-023e72a1d4b1",
            "life-span": {
                "begin": "2012",
                "ended": null
            },
            "name": "The Nirvana Experience",
            "score": "50",
            "sort-name": "The Nirvana Experience",
            "type": "Group"
        },
        {
            "id": "e43ad11b-5d29-45ae-90f7-73ac47fb815d",
            "life-span": {
                "ended": null
            },
            "name": "smells like nirvana",
            "score": "50",
            "sort-name": "smells like nirvana"
        },
        {
            "area": {
                "id": "5b8a5ee5-0bb3-34cf-9a75-c27c44e341fc",
                "name": "Belgium",
                "sort-name": "Belgium"
            },
            "country": "BE",
            "disambiguation": "Belgian",
            "id": "1d512080-0ef7-454f-a325-9bf5ff95ce88",
            "life-span": {
                "ended": null
            },
            "name": "Come As Nirvana",
            "score": "50",
            "sort-name": "Come As Nirvana",
            "type": "Group"
        },
        {
            "id": "e1388435-f80d-434a-9980-f1c9f5aa9b90",
            "life-span": {
                "ended": null
            },
            "name": "Nirvana Sitar & String Group",
            "score": "43",
            "sort-name": "Nirvana Sitar & String Group"
        }
    ],
    "count": 21,
    "created": "2018-03-12T23:26:58.989Z",
    "offset": 0
}

In [54]:
results.keys()

dict_keys(['created', 'count', 'offset', 'artists'])

In [60]:
print("\nARTIST:")
pretty_print(results["artists"][4])

ARTIST:
{
    "aliases": [
        {
            "begin-date": null,
            "end-date": null,
            "locale": null,
            "name": "Nirvana US",
            "primary": null,
            "sort-name": "Nirvana US",
            "type": null
        }
    ],
    "area": {
        "id": "489ce91b-6658-3307-9877-795b68554c98",
        "name": "United States",
        "sort-name": "United States"
    },
    "begin-area": {
        "id": "a640b45c-c173-49b1-8030-973603e895b5",
        "name": "Aberdeen",
        "sort-name": "Aberdeen"
    },
    "country": "US",
    "disambiguation": "90s US grunge band",
    "id": "5b11f4ce-a62d-471e-81fc-a69a8278c7da",
    "life-span": {
        "begin": "1988-01",
        "end": "1994-04-05",
        "ended": true
    },
    "name": "Nirvana",
    "score": "100",
    "sort-name": "Nirvana",
    "tags": [
        {
            "count": 9,
            "name": "rock"
        },
        {
            "count": 4,
            "name": "alternative rock"
        },
        {
            "count": 1,
            "name": "90s"
        },
        {
            "count": 1,
            "name": "punk"
        },
        {
            "count": 5,
            "name": "american"
        },
        {
            "count": 1,
            "name": "seattle"
        },
        {
            "count": 14,
            "name": "grunge"
        },
        {
            "count": 0,
            "name": "band"
        },
        {
            "count": 1,
            "name": "usa"
        },
        {
            "count": 0,
            "name": "alternative"
        },
        {
            "count": 0,
            "name": "am\u00e9ricain"
        },
        {
            "count": 0,
            "name": "legendary"
        },
        {
            "count": 1,
            "name": "acoustic rock"
        },
        {
            "count": 1,
            "name": "noise rock"
        },
        {
            "count": 0,
            "name": "90"
        },
        {
            "count": 0,
            "name": "northwest"
        },
        {
            "count": 0,
            "name": "rock and indie"
        },
        {
            "count": 0,
            "name": "united states"
        },
        {
            "count": 0,
            "name": "nirvana"
        },
        {
            "count": 0,
            "name": "kurt cobain"
        }
    ],
    "type": "Group"
}

In [63]:
artist_id = results["artists"][4]["id"]
artist_id

'5b11f4ce-a62d-471e-81fc-a69a8278c7da'

In [64]:
artist_data = query_site(artist_url, query_type["releases"], artist_id)
releases = artist_data["releases"]
print("\nONE RELEASE:")
pretty_print(releases[0], indent=2)

requesting http://musicbrainz.org/ws/2/artist/5b11f4ce-a62d-471e-81fc-a69a8278c7da?inc=releases&fmt=json

ONE RELEASE:
{
  "barcode": "",
  "country": "US",
  "date": "1990-01",
  "disambiguation": "",
  "id": "0444b84e-15af-47a4-810a-773258eb9395",
  "packaging": "Cardboard/Paper Sleeve",
  "packaging-id": "f7101ce3-0384-39ce-9fde-fbbd0044d35f",
  "quality": "normal",
  "release-events": [
    {
      "area": {
        "disambiguation": "",
        "id": "489ce91b-6658-3307-9877-795b68554c98",
        "iso-3166-1-codes": [
          "US"
        ],
        "name": "United States",
        "sort-name": "United States"
      },
      "date": "1990-01"
    }
  ],
  "status": "Official",
  "status-id": "4e304316-386d-3409-af2e-78857eec5cfe",
  "text-representation": {
    "language": "eng",
    "script": "Latn"
  },
  "title": "Never Mind the Bollocks Here\u2019s Nirvana"
}

In [65]:
releases

[{'barcode': '',
  'country': 'US',
  'date': '1990-01',
  'disambiguation': '',
  'id': '0444b84e-15af-47a4-810a-773258eb9395',
  'packaging': 'Cardboard/Paper Sleeve',
  'packaging-id': 'f7101ce3-0384-39ce-9fde-fbbd0044d35f',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1990-01'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Never Mind the Bollocks Here’s Nirvana'},
 {'barcode': '5018615200826',
  'country': 'GB',
  'date': '1989-12',
  'disambiguation': '',
  'id': '180abab4-8480-4d1b-9a9c-db3d5e864390',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
     'iso-3166-1-codes': ['GB'],
     'name': 'United Kingdom',
     'sort-name': 'United Kingdom'},
    'date': '1989-12'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Blew'},
 {'barcode': '5018615202561',
  'country': 'GB',
  'date': '1991-01-21',
  'disambiguation': '',
  'id': '1a5ad2ee-92e6-47a5-9340-25c529fc39b4',
  'packaging': 'Cardboard/Paper Sleeve',
  'packaging-id': 'f7101ce3-0384-39ce-9fde-fbbd0044d35f',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
     'iso-3166-1-codes': ['GB'],
     'name': 'United Kingdom',
     'sort-name': 'United Kingdom'},
    'date': '1991-01-21'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Sliver'},
 {'barcode': None,
  'country': 'PL',
  'date': '1990',
  'disambiguation': '',
  'id': '202368dc-5497-47a3-953e-bfa631b2a0cb',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': 'dd7f80c8-f017-3d01-8608-2a8c9c32b954',
     'iso-3166-1-codes': ['PL'],
     'name': 'Poland',
     'sort-name': 'Poland'},
    'date': '1990'}],
  'status': 'Bootleg',
  'status-id': '1156806e-d06a-38bd-83f0-cf2284a808b9',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Bleach'},
 {'barcode': None,
  'country': 'US',
  'date': '1990-09',
  'disambiguation': '',
  'id': '21c3ed4e-3961-3fa3-9541-e4f02a980858',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1990-09'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Sliver'},
 {'barcode': None,
  'country': 'US',
  'date': '1988-11',
  'disambiguation': '',
  'id': '2c84c9b3-d1d4-48c0-a825-a360f26a5dde',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1988-11'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Love Buzz / Big Cheese'},
 {'barcode': None,
  'country': 'US',
  'date': '1991-09-10',
  'disambiguation': '',
  'id': '2f03daed-36e6-4b17-8df3-6dc49556f438',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1991-09-10'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Smells Like Teen Spirit'},
 {'barcode': '720642167328',
  'country': 'XE',
  'date': '1991-09-10',
  'disambiguation': '',
  'id': '3abad285-fd57-4709-9f82-572b9c1ae051',
  'packaging': 'Slim Jewel Case',
  'packaging-id': '36327bc2-f691-3d66-80e5-bd03cec6060a',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '89a675c2-3e37-3518-b83c-418bad59a85a',
     'iso-3166-1-codes': ['XE'],
     'name': 'Europe',
     'sort-name': 'Europe'},
    'date': '1991-09-10'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Smells Like Teen Spirit'},
 {'barcode': None,
  'country': 'US',
  'date': '1991-06',
  'disambiguation': '',
  'id': '3fce74e6-2898-478e-81b3-c72a8fb4cb89',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1991-06'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Here She Comes Now / Venus in Furs'},
 {'barcode': '720642167328',
  'country': 'DE',
  'date': '1991-09-10',
  'disambiguation': '',
  'id': '68f9fe0a-23c2-3975-8310-7f675b4ec0e6',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '85752fda-13c4-31a3-bee5-0e5cb1f51dad',
     'iso-3166-1-codes': ['DE'],
     'name': 'Germany',
     'sort-name': 'Germany'},
    'date': '1991-09-10'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Smells Like Teen Spirit'},
 {'barcode': '720642167328',
  'country': 'US',
  'date': '1991-09-10',
  'disambiguation': '',
  'id': '6a3e3fe7-3cc5-3a6d-b3aa-6fbb12d5b9b2',
  'packaging': 'Digipak',
  'packaging-id': '8f931351-d2e2-310f-afc6-37b89ddba246',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1991-09-10'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Smells Like Teen Spirit'},
 {'barcode': '098787003420',
  'country': 'US',
  'date': '1989-06-01',
  'disambiguation': '',
  'id': '7d166a44-cfb5-4b08-aacb-6863bbe677d6',
  'packaging': 'Jewel Case',
  'packaging-id': 'ec27701a-4a22-37f4-bfac-6616e0f9750a',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1989-06-01'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Bleach'},
 {'barcode': '5018615202523',
  'country': 'GB',
  'date': '1991-01',
  'disambiguation': '',
  'id': '7f183c32-4a79-4873-ac38-215cde83e0ce',
  'packaging': 'Slim Jewel Case',
  'packaging-id': '36327bc2-f691-3d66-80e5-bd03cec6060a',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
     'iso-3166-1-codes': ['GB'],
     'name': 'United Kingdom',
     'sort-name': 'United Kingdom'},
    'date': '1991-01'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Sliver'},
 {'barcode': None,
  'country': 'US',
  'date': '1991-09-10',
  'disambiguation': '',
  'id': '8d771949-da8f-36df-8d4a-c3cb194cf21d',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1991-09-10'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Smells Like Teen Spirit'},
 {'barcode': '5018615200819',
  'country': 'GB',
  'date': '1989-12',
  'disambiguation': '',
  'id': 'a5829c6e-ad99-38cf-bf98-2dcbee359c09',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
     'iso-3166-1-codes': ['GB'],
     'name': 'United Kingdom',
     'sort-name': 'United Kingdom'},
    'date': '1989-12'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Blew'},
 {'barcode': '',
  'country': 'US',
  'date': '1991-01',
  'disambiguation': '',
  'id': 'a8b2b2e8-f366-4903-afe8-d4ca1332c13d',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1991-01'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Candy / Molly’s Lips'},
 {'barcode': '008811929121',
  'country': None,
  'date': '1989',
  'disambiguation': '',
  'id': 'a96b59a5-4185-4d87-899a-a0d944385811',
  'packaging': 'Jewel Case',
  'packaging-id': 'ec27701a-4a22-37f4-bfac-6616e0f9750a',
  'quality': 'normal',
  'release-events': [{'area': None, 'date': '1989'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Bleach'},
 {'barcode': None,
  'country': 'US',
  'date': '1990-09',
  'disambiguation': '',
  'id': 'acebbf06-a948-46e7-ae3c-730894e08067',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1990-09'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Sliver'},
 {'barcode': '5021509000525',
  'country': 'GB',
  'date': '1991-09-10',
  'disambiguation': '',
  'id': 'b0dd957a-4dd0-40e3-920c-3aac782fad14',
  'packaging': 'Digipak',
  'packaging-id': '8f931351-d2e2-310f-afc6-37b89ddba246',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
     'iso-3166-1-codes': ['GB'],
     'name': 'United Kingdom',
     'sort-name': 'United Kingdom'},
    'date': '1991-09-10'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Smells Like Teen Spirit'},
 {'barcode': '720642442524',
  'country': 'XE',
  'date': '1991-09-23',
  'disambiguation': '',
  'id': 'b52a8f31-b5ab-34e9-92f4-f5b7110220f0',
  'packaging': 'Jewel Case',
  'packaging-id': 'ec27701a-4a22-37f4-bfac-6616e0f9750a',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '89a675c2-3e37-3518-b83c-418bad59a85a',
     'iso-3166-1-codes': ['XE'],
     'name': 'Europe',
     'sort-name': 'Europe'},
    'date': '1991-09-23'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Nevermind'},
 {'barcode': '5018615200628',
  'country': 'GB',
  'date': '1989',
  'disambiguation': '',
  'id': 'd3d44548-b2ed-3ddc-a9e0-3f5ee544c1c9',
  'packaging': 'Jewel Case',
  'packaging-id': 'ec27701a-4a22-37f4-bfac-6616e0f9750a',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
     'iso-3166-1-codes': ['GB'],
     'name': 'United Kingdom',
     'sort-name': 'United Kingdom'},
    'date': '1989'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Bleach'},
 {'barcode': None,
  'country': 'US',
  'date': '1991-09-10',
  'disambiguation': '',
  'id': 'e1c5d5fa-b1cb-388b-9027-055aa29a382b',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1991-09-10'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Smells Like Teen Spirit'},
 {'barcode': None,
  'country': 'US',
  'date': '1989-08-08',
  'disambiguation': '',
  'id': 'e5fa1cc5-3693-455a-821f-5ace2690aff1',
  'packaging': None,
  'packaging-id': None,
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1989-08-08'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Bleach'},
 {'barcode': '',
  'country': 'US',
  'date': '1990-09',
  'disambiguation': '',
  'id': 'eaff5199-b86c-4bca-a4b5-c7c33e10e88d',
  'packaging': 'Cardboard/Paper Sleeve',
  'packaging-id': 'f7101ce3-0384-39ce-9fde-fbbd0044d35f',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'name': 'United States',
     'sort-name': 'United States'},
    'date': '1990-09'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Sliver'},
 {'barcode': '720642442524',
  'country': 'AU',
  'date': '1991-09-24',
  'disambiguation': '',
  'id': 'eccae410-7577-4daa-b602-92d305828331',
  'packaging': 'Jewel Case',
  'packaging-id': 'ec27701a-4a22-37f4-bfac-6616e0f9750a',
  'quality': 'normal',
  'release-events': [{'area': {'disambiguation': '',
     'id': '106e0bec-b638-3b37-b731-f53d507dc00e',
     'iso-3166-1-codes': ['AU'],
     'name': 'Australia',
     'sort-name': 'Australia'},
    'date': '1991-09-24'}],
  'status': 'Official',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'title': 'Nevermind'}]

In [66]:
release_titles = [r["title"] for r in releases]
print("\nALL TITLES:")
for t in release_titles:
        print(t)

ALL TITLES:
Never Mind the Bollocks Here’s Nirvana
Blew
Sliver
Bleach
Sliver
Love Buzz / Big Cheese
Smells Like Teen Spirit
Smells Like Teen Spirit
Here She Comes Now / Venus in Furs
Smells Like Teen Spirit
Smells Like Teen Spirit
Bleach
Sliver
Smells Like Teen Spirit
Blew
Candy / Molly’s Lips
Bleach
Sliver
Smells Like Teen Spirit
Nevermind
Bleach
Smells Like Teen Spirit
Bleach
Sliver
Nevermind

#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader

In [67]:
df_json = pd.read_json('https://api.github.com/repos/pydata/pandas/issues?per_page=5')
df_json

,assignee,assignees,author_association,body,closed_at,comments,comments_url,created_at,events_url,html_url,...,locked,milestone,number,pull_request,repository_url,state,title,updated_at,url,user
0,NaN,[],NONE,"Hello,\r\n\r\nI'm newbie in Panda. I want to g...",NaT,0,https://api.github.com/repos/pandas-dev/pandas...,2018-03-12 22:39:31,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20317,...,False,NaN,20317,NaN,https://api.github.com/repos/pandas-dev/pandas,open,Cannot access callable attribute 'groupby' of ...,2018-03-12 22:39:31,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'ymhiri', 'id': 37225237, 'avatar_ur..."
1,NaN,[],NONE,Checklist for the pandas documentation sprint ...,NaT,1,https://api.github.com/repos/pandas-dev/pandas...,2018-03-12 20:52:17,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/20316,...,False,NaN,20316,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas,open,DOC: update the day_name function docstring,2018-03-12 21:23:35,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'NeehaK', 'id': 37204553, 'avatar_ur..."
2,NaN,[],NONE,Checklist for the pandas documentation sprint ...,NaT,1,https://api.github.com/repos/pandas-dev/pandas...,2018-03-12 20:36:37,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/20315,...,False,NaN,20315,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas,open,DOC: update the pandas.Series.add_suffix docst...,2018-03-12 23:09:39,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'astrastefania', 'id': 1804766, 'ava..."
3,NaN,[],NONE,Checklist for the pandas documentation sprint ...,NaT,0,https://api.github.com/repos/pandas-dev/pandas...,2018-03-12 20:17:40,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/20313,...,False,NaN,20313,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas,open,DOC: update docstring of pandas.Series.add_pre...,2018-03-12 23:08:42,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'astrastefania', 'id': 1804766, 'ava..."
4,NaN,[],OWNER,I merged the docstring guide https://github.co...,NaT,5,https://api.github.com/repos/pandas-dev/pandas...,2018-03-12 17:43:59,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20309,...,False,NaN,20309,NaN,https://api.github.com/repos/pandas-dev/pandas,open,DOC: further clarifications to docstring guide,2018-03-12 22:01:28,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'jorisvandenbossche', 'id': 1020496,..."

## Accessing XML

https://docs.python.org/3/library/urllib.html

https://docs.python.org/3/library/xml.etree.elementtree.html

http://lxml.de/

http://www.w3schools.com/xml/xml_examples.asp

In [68]:
from xml.dom import minidom
#from xml.etree import ElementTree as ET
from lxml import etree as ET #Supports xpath syntax
from collections import defaultdict
from pprint import pprint

In [69]:
url = 'http://www.w3schools.com/xml/cd_catalog.xml'
xml_page = urllib.request.urlopen(url).read()
e = ET.XML(xml_page)

In [70]:
def etree_to_dict(t):
    d = {t.tag: {} if t.attrib else None}
    children = list(t)
    if children:
        dd = defaultdict(list)
        for dc in map(etree_to_dict, children):
            for k, v in dc.items():
                dd[k].append(v)
        d = {t.tag: {k:v[0] if len(v) == 1 else v for k, v in dd.items()}}
    if t.attrib:
        d[t.tag].update(('@' + k, v) for k, v in t.attrib.items())
    if t.text:
        text = t.text.strip()
        if children or t.attrib:
            if text:
              d[t.tag]['#text'] = text
        else:
            d[t.tag] = text
    return d

In [71]:
pprint(etree_to_dict(e))

{'CATALOG': {'CD': [{'ARTIST': 'Bob Dylan',
                     'COMPANY': 'Columbia',
                     'COUNTRY': 'USA',
                     'PRICE': '10.90',
                     'TITLE': 'Empire Burlesque',
                     'YEAR': '1985'},
                    {'ARTIST': 'Bonnie Tyler',
                     'COMPANY': 'CBS Records',
                     'COUNTRY': 'UK',
                     'PRICE': '9.90',
                     'TITLE': 'Hide your heart',
                     'YEAR': '1988'},
                    {'ARTIST': 'Dolly Parton',
                     'COMPANY': 'RCA',
                     'COUNTRY': 'USA',
                     'PRICE': '9.90',
                     'TITLE': 'Greatest Hits',
                     'YEAR': '1982'},
                    {'ARTIST': 'Gary Moore',
                     'COMPANY': 'Virgin records',
                     'COUNTRY': 'UK',
                     'PRICE': '10.20',
                     'TITLE': 'Still got the blues',
                     'YEAR': '1990'},
                    {'ARTIST': 'Eros Ramazzotti',
                     'COMPANY': 'BMG',
                     'COUNTRY': 'EU',
                     'PRICE': '9.90',
                     'TITLE': 'Eros',
                     'YEAR': '1997'},
                    {'ARTIST': 'Bee Gees',
                     'COMPANY': 'Polydor',
                     'COUNTRY': 'UK',
                     'PRICE': '10.90',
                     'TITLE': 'One night only',
                     'YEAR': '1998'},
                    {'ARTIST': 'Dr.Hook',
                     'COMPANY': 'CBS',
                     'COUNTRY': 'UK',
                     'PRICE': '8.10',
                     'TITLE': 'Sylvias Mother',
                     'YEAR': '1973'},
                    {'ARTIST': 'Rod Stewart',
                     'COMPANY': 'Pickwick',
                     'COUNTRY': 'UK',
                     'PRICE': '8.50',
                     'TITLE': 'Maggie May',
                     'YEAR': '1990'},
                    {'ARTIST': 'Andrea Bocelli',
                     'COMPANY': 'Polydor',
                     'COUNTRY': 'EU',
                     'PRICE': '10.80',
                     'TITLE': 'Romanza',
                     'YEAR': '1996'},
                    {'ARTIST': 'Percy Sledge',
                     'COMPANY': 'Atlantic',
                     'COUNTRY': 'USA',
                     'PRICE': '8.70',
                     'TITLE': 'When a man loves a woman',
                     'YEAR': '1987'},
                    {'ARTIST': 'Savage Rose',
                     'COMPANY': 'Mega',
                     'COUNTRY': 'EU',
                     'PRICE': '10.90',
                     'TITLE': 'Black angel',
                     'YEAR': '1995'},
                    {'ARTIST': 'Many',
                     'COMPANY': 'Grammy',
                     'COUNTRY': 'USA',
                     'PRICE': '10.20',
                     'TITLE': '1999 Grammy Nominees',
                     'YEAR': '1999'},
                    {'ARTIST': 'Kenny Rogers',
                     'COMPANY': 'Mucik Master',
                     'COUNTRY': 'UK',
                     'PRICE': '8.70',
                     'TITLE': 'For the good times',
                     'YEAR': '1995'},
                    {'ARTIST': 'Will Smith',
                     'COMPANY': 'Columbia',
                     'COUNTRY': 'USA',
                     'PRICE': '9.90',
                     'TITLE': 'Big Willie style',
                     'YEAR': '1997'},
                    {'ARTIST': 'Van Morrison',
                     'COMPANY': 'Polydor',
                     'COUNTRY': 'UK',
                     'PRICE': '8.20',
                     'TITLE': 'Tupelo Honey',
                     'YEAR': '1971'},
                    {'ARTIST': 'Jorn Hoel',
                     'COMPANY': 'WEA',
                     'COUNTRY': 'Norway',
                     'PRICE': '7.90',
                     'TITLE': 'Soulsville',
                     'YEAR': '1996'},
                    {'ARTIST': 'Cat Stevens',
                     'COMPANY': 'Island',
                     'COUNTRY': 'UK',
                     'PRICE': '8.90',
                     'TITLE': 'The very best of',
                     'YEAR': '1990'},
                    {'ARTIST': 'Sam Brown',
                     'COMPANY': 'A and M',
                     'COUNTRY': 'UK',
                     'PRICE': '8.90',
                     'TITLE': 'Stop',
                     'YEAR': '1988'},
                    {'ARTIST': "T'Pau",
                     'COMPANY': 'Siren',
                     'COUNTRY': 'UK',
                     'PRICE': '7.90',
                     'TITLE': 'Bridge of Spies',
                     'YEAR': '1987'},
                    {'ARTIST': 'Tina Turner',
                     'COMPANY': 'Capitol',
                     'COUNTRY': 'UK',
                     'PRICE': '8.90',
                     'TITLE': 'Private Dancer',
                     'YEAR': '1983'},
                    {'ARTIST': 'Kim Larsen',
                     'COMPANY': 'Medley',
                     'COUNTRY': 'EU',
                     'PRICE': '7.80',
                     'TITLE': 'Midt om natten',
                     'YEAR': '1983'},
                    {'ARTIST': 'Luciano Pavarotti',
                     'COMPANY': 'DECCA',
                     'COUNTRY': 'UK',
                     'PRICE': '9.90',
                     'TITLE': 'Pavarotti Gala Concert',
                     'YEAR': '1991'},
                    {'ARTIST': 'Otis Redding',
                     'COMPANY': 'Stax Records',
                     'COUNTRY': 'USA',
                     'PRICE': '7.90',
                     'TITLE': 'The dock of the bay',
                     'YEAR': '1968'},
                    {'ARTIST': 'Simply Red',
                     'COMPANY': 'Elektra',
                     'COUNTRY': 'EU',
                     'PRICE': '7.20',
                     'TITLE': 'Picture book',
                     'YEAR': '1985'},
                    {'ARTIST': 'The Communards',
                     'COMPANY': 'London',
                     'COUNTRY': 'UK',
                     'PRICE': '7.80',
                     'TITLE': 'Red',
                     'YEAR': '1987'},
                    {'ARTIST': 'Joe Cocker',
                     'COMPANY': 'EMI',
                     'COUNTRY': 'USA',
                     'PRICE': '8.20',
                     'TITLE': 'Unchain my heart',
                     'YEAR': '1987'}]}}

In [73]:
raw_page = urllib.request.urlopen(url)
doc = minidom.parse(raw_page)

def findTextnodes(nodeList):
    for subnode in nodeList:
        if subnode.nodeType == subnode.ELEMENT_NODE:
            print("Element node: " + subnode.tagName)
            findTextnodes(subnode.childNodes)
        elif subnode.nodeType == subnode.TEXT_NODE:
            print("text node:" + subnode.data)
            
findTextnodes(doc.childNodes)

Element node: CATALOG
text node:

Element node: CD
text node:

Element node: TITLE
text node:Empire Burlesque
text node:

Element node: ARTIST
text node:Bob Dylan
text node:

Element node: COUNTRY
text node:USA
text node:

Element node: COMPANY
text node:Columbia
text node:

Element node: PRICE
text node:10.90
text node:

Element node: YEAR
text node:1985
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Hide your heart
text node:

Element node: ARTIST
text node:Bonnie Tyler
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:CBS Records
text node:

Element node: PRICE
text node:9.90
text node:

Element node: YEAR
text node:1988
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Greatest Hits
text node:

Element node: ARTIST
text node:Dolly Parton
text node:

Element node: COUNTRY
text node:USA
text node:

Element node: COMPANY
text node:RCA
text node:

Element node: PRICE
text node:9.90
text node:

Element node: YEAR
text node:1982
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Still got the blues
text node:

Element node: ARTIST
text node:Gary Moore
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Virgin records
text node:

Element node: PRICE
text node:10.20
text node:

Element node: YEAR
text node:1990
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Eros
text node:

Element node: ARTIST
text node:Eros Ramazzotti
text node:

Element node: COUNTRY
text node:EU
text node:

Element node: COMPANY
text node:BMG
text node:

Element node: PRICE
text node:9.90
text node:

Element node: YEAR
text node:1997
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:One night only
text node:

Element node: ARTIST
text node:Bee Gees
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Polydor
text node:

Element node: PRICE
text node:10.90
text node:

Element node: YEAR
text node:1998
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Sylvias Mother
text node:

Element node: ARTIST
text node:Dr.Hook
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:CBS
text node:

Element node: PRICE
text node:8.10
text node:

Element node: YEAR
text node:1973
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Maggie May
text node:

Element node: ARTIST
text node:Rod Stewart
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Pickwick
text node:

Element node: PRICE
text node:8.50
text node:

Element node: YEAR
text node:1990
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Romanza
text node:

Element node: ARTIST
text node:Andrea Bocelli
text node:

Element node: COUNTRY
text node:EU
text node:

Element node: COMPANY
text node:Polydor
text node:

Element node: PRICE
text node:10.80
text node:

Element node: YEAR
text node:1996
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:When a man loves a woman
text node:

Element node: ARTIST
text node:Percy Sledge
text node:

Element node: COUNTRY
text node:USA
text node:

Element node: COMPANY
text node:Atlantic
text node:

Element node: PRICE
text node:8.70
text node:

Element node: YEAR
text node:1987
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Black angel
text node:

Element node: ARTIST
text node:Savage Rose
text node:

Element node: COUNTRY
text node:EU
text node:

Element node: COMPANY
text node:Mega
text node:

Element node: PRICE
text node:10.90
text node:

Element node: YEAR
text node:1995
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:1999 Grammy Nominees
text node:

Element node: ARTIST
text node:Many
text node:

Element node: COUNTRY
text node:USA
text node:

Element node: COMPANY
text node:Grammy
text node:

Element node: PRICE
text node:10.20
text node:

Element node: YEAR
text node:1999
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:For the good times
text node:

Element node: ARTIST
text node:Kenny Rogers
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Mucik Master
text node:

Element node: PRICE
text node:8.70
text node:

Element node: YEAR
text node:1995
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Big Willie style
text node:

Element node: ARTIST
text node:Will Smith
text node:

Element node: COUNTRY
text node:USA
text node:

Element node: COMPANY
text node:Columbia
text node:

Element node: PRICE
text node:9.90
text node:

Element node: YEAR
text node:1997
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Tupelo Honey
text node:

Element node: ARTIST
text node:Van Morrison
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Polydor
text node:

Element node: PRICE
text node:8.20
text node:

Element node: YEAR
text node:1971
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Soulsville
text node:

Element node: ARTIST
text node:Jorn Hoel
text node:

Element node: COUNTRY
text node:Norway
text node:

Element node: COMPANY
text node:WEA
text node:

Element node: PRICE
text node:7.90
text node:

Element node: YEAR
text node:1996
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:The very best of
text node:

Element node: ARTIST
text node:Cat Stevens
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Island
text node:

Element node: PRICE
text node:8.90
text node:

Element node: YEAR
text node:1990
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Stop
text node:

Element node: ARTIST
text node:Sam Brown
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:A and M
text node:

Element node: PRICE
text node:8.90
text node:

Element node: YEAR
text node:1988
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Bridge of Spies
text node:

Element node: ARTIST
text node:T'Pau
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Siren
text node:

Element node: PRICE
text node:7.90
text node:

Element node: YEAR
text node:1987
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Private Dancer
text node:

Element node: ARTIST
text node:Tina Turner
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:Capitol
text node:

Element node: PRICE
text node:8.90
text node:

Element node: YEAR
text node:1983
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Midt om natten
text node:

Element node: ARTIST
text node:Kim Larsen
text node:

Element node: COUNTRY
text node:EU
text node:

Element node: COMPANY
text node:Medley
text node:

Element node: PRICE
text node:7.80
text node:

Element node: YEAR
text node:1983
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Pavarotti Gala Concert
text node:

Element node: ARTIST
text node:Luciano Pavarotti
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:DECCA
text node:

Element node: PRICE
text node:9.90
text node:

Element node: YEAR
text node:1991
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:The dock of the bay
text node:

Element node: ARTIST
text node:Otis Redding
text node:

Element node: COUNTRY
text node:USA
text node:

Element node: COMPANY
text node:Stax Records
text node:

Element node: PRICE
text node:7.90
text node:

Element node: YEAR
text node:1968
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Picture book
text node:

Element node: ARTIST
text node:Simply Red
text node:

Element node: COUNTRY
text node:EU
text node:

Element node: COMPANY
text node:Elektra
text node:

Element node: PRICE
text node:7.20
text node:

Element node: YEAR
text node:1985
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Red
text node:

Element node: ARTIST
text node:The Communards
text node:

Element node: COUNTRY
text node:UK
text node:

Element node: COMPANY
text node:London
text node:

Element node: PRICE
text node:7.80
text node:

Element node: YEAR
text node:1987
text node:

text node:

Element node: CD
text node:

Element node: TITLE
text node:Unchain my heart
text node:

Element node: ARTIST
text node:Joe Cocker
text node:

Element node: COUNTRY
text node:USA
text node:

Element node: COMPANY
text node:EMI
text node:

Element node: PRICE
text node:8.20
text node:

Element node: YEAR
text node:1987
text node:

text node:

In [74]:
root = ET.fromstring(xml_page)
cdtags = root.xpath('//CD/TITLE')
for cd in cdtags:
    print(cd.text)

Empire Burlesque
Hide your heart
Greatest Hits
Still got the blues
Eros
One night only
Sylvias Mother
Maggie May
Romanza
When a man loves a woman
Black angel
1999 Grammy Nominees
For the good times
Big Willie style
Tupelo Honey
Soulsville
The very best of
Stop
Bridge of Spies
Private Dancer
Midt om natten
Pavarotti Gala Concert
The dock of the bay
Picture book
Red
Unchain my heart

In [75]:
for cd in root.findall('CD'):
    title = cd.find('TITLE').text
    artist = cd.find('ARTIST').text
    country = cd.find('COUNTRY').text
    print('{}\t{}\t{}'.format(artist, country, title))

Bob Dylan	USA	Empire Burlesque
Bonnie Tyler	UK	Hide your heart
Dolly Parton	USA	Greatest Hits
Gary Moore	UK	Still got the blues
Eros Ramazzotti	EU	Eros
Bee Gees	UK	One night only
Dr.Hook	UK	Sylvias Mother
Rod Stewart	UK	Maggie May
Andrea Bocelli	EU	Romanza
Percy Sledge	USA	When a man loves a woman
Savage Rose	EU	Black angel
Many	USA	1999 Grammy Nominees
Kenny Rogers	UK	For the good times
Will Smith	USA	Big Willie style
Van Morrison	UK	Tupelo Honey
Jorn Hoel	Norway	Soulsville
Cat Stevens	UK	The very best of
Sam Brown	UK	Stop
T'Pau	UK	Bridge of Spies
Tina Turner	UK	Private Dancer
Kim Larsen	EU	Midt om natten
Luciano Pavarotti	UK	Pavarotti Gala Concert
Otis Redding	USA	The dock of the bay
Simply Red	EU	Picture book
The Communards	UK	Red
Joe Cocker	USA	Unchain my heart

In [76]:
cds = []
for cd in root.findall('./CD'):
        data = {}
        data["TITLE"] = cd.find('./TITLE').text
        data["ARTIST"] = cd.find('./ARTIST').text
        data["COUNTRY"] = cd.find('./COUNTRY').text
        data["PRICE"] = cd.find('./PRICE').text
        data["YEAR"] = cd.find('./YEAR').text
        cds.append(data)
cds[0:3]

[{'ARTIST': 'Bob Dylan',
  'COUNTRY': 'USA',
  'PRICE': '10.90',
  'TITLE': 'Empire Burlesque',
  'YEAR': '1985'},
 {'ARTIST': 'Bonnie Tyler',
  'COUNTRY': 'UK',
  'PRICE': '9.90',
  'TITLE': 'Hide your heart',
  'YEAR': '1988'},
 {'ARTIST': 'Dolly Parton',
  'COUNTRY': 'USA',
  'PRICE': '9.90',
  'TITLE': 'Greatest Hits',
  'YEAR': '1982'}]

## Acessing Databases

### Acessing SQLite

https://docs.python.org/3/library/sqlite3.html

In [90]:
import sqlite3
conn = sqlite3.connect(os.path.join(outputs,'example.db'))

In [81]:
c = conn.cursor()

# Create table
c.execute('''CREATE TABLE IF NOT EXISTS stocks
             (date text, trans text, symbol text, qty real, price real)''')

# Insert a row of data
c.execute("INSERT INTO stocks VALUES ('2006-01-05','BUY','RHAT',100,35.14)")

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()

In [82]:
conn = sqlite3.connect(os.path.join(outputs,'example.db'))
c = conn.cursor()

In [83]:
t = ('RHAT',) #tuple with just one element
c.execute('SELECT * FROM stocks WHERE symbol=?', t)
print(c.fetchone())

('2006-01-05', 'BUY', 'RHAT', 100.0, 35.14)

In [84]:
# Larger example that inserts many records at a time
purchases = [('2006-03-28', 'BUY', 'IBM', 1000, 45.00),
             ('2006-04-05', 'BUY', 'MSFT', 1000, 72.00),
             ('2006-04-06', 'SELL', 'IBM', 500, 53.00),
            ]
c.executemany('INSERT INTO stocks VALUES (?,?,?,?,?)', purchases)

In [85]:
for row in c.execute('SELECT * FROM stocks ORDER BY price'):
        print(row)

('2006-01-05', 'BUY', 'RHAT', 100.0, 35.14)
('2006-03-28', 'BUY', 'IBM', 1000.0, 45.0)
('2006-04-06', 'SELL', 'IBM', 500.0, 53.0)
('2006-04-05', 'BUY', 'MSFT', 1000.0, 72.0)

#### Using Pandas

In [86]:
conn = sqlite3.connect(os.path.join(outputs,'example.db'))
df = pd.read_sql_query("SELECT * from stocks ORDER BY price", conn)

# verify that result of SQL query is stored in the dataframe
print(df.head())

conn.close()

         date trans symbol    qty  price
0  2006-01-05   BUY   RHAT  100.0  35.14

Deleting the database file:

In [91]:
os.remove(os.path.join(outputs,'example.db'))

### Acessing MySQL

https://pypi.python.org/pypi/PyMySQL

In [92]:
import pymysql

In [94]:
p = getpass.getpass()
conn = pymysql.connect(host='localhost', port=3306, user='root', passwd=p,)# db='example')
cur = conn.cursor()

In [95]:
cur.execute("show databases;")
for r in cur.fetchall():
   print(r)

('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [96]:
cur.execute("use mysql;")
cur.execute("show tables;")
for r in cur.fetchall():
   print(r)

('columns_priv',)
('db',)
('engine_cost',)
('event',)
('func',)
('general_log',)
('gtid_executed',)
('help_category',)
('help_keyword',)
('help_relation',)
('help_topic',)
('innodb_index_stats',)
('innodb_table_stats',)
('ndb_binlog_index',)
('plugin',)
('proc',)
('procs_priv',)
('proxies_priv',)
('server_cost',)
('servers',)
('slave_master_info',)
('slave_relay_log_info',)
('slave_worker_info',)
('slow_log',)
('tables_priv',)
('time_zone',)
('time_zone_leap_second',)
('time_zone_name',)
('time_zone_transition',)
('time_zone_transition_type',)
('user',)

In [97]:
cur.execute("CREATE DATABASE IF NOT EXISTS test;")
cur.execute("USE test;")
cur.execute('''CREATE TABLE IF NOT EXISTS test_table 
               (text VARCHAR(200)
               DEFAULT NULL)
               ENGINE=MyISAM DEFAULT CHARSET='utf8';''')

cur.execute("show tables;")
for r in cur.fetchall():
   print(r)

('test_table',)

In [98]:
texts = ['It always seems impossible until its done.',
         'In order to succeed, we must first believe that we can.',
         'Life is 10% what happens to you and 90% how you react to it.',
         'Start where you are. Use what you have. Do what you can.',]
cur.executemany('INSERT INTO test.test_table (text) VALUES (%s)', texts)

4

In [99]:
cur.execute("SELECT * FROM test.test_table;")# LIMIT 10;")
for r in cur.fetchall():
   print(r)

('It always seems impossible until its done.',)
('In order to succeed, we must first believe that we can.',)
('Life is 10% what happens to you and 90% how you react to it.',)
('Start where you are. Use what you have. Do what you can.',)

#### Using Pandas

In [100]:
import pandas.io.sql as psql

In [101]:
df_mysql = psql.read_sql('select * from test.test_table;', con=conn)

In [102]:
df_mysql.head()

                                                text
0         It always seems impossible until its done.
1  In order to succeed, we must first believe tha...
2  Life is 10% what happens to you and 90% how yo...
3  Start where you are. Use what you have. Do wha...

In [103]:
cur.close()
conn.close()

### Acessing PostgreSQL

In [124]:
import psycopg2

In [130]:
p = getpass.getpass()
try:
    conn = psycopg2.connect("dbname='testdb' user='rsouza' host='localhost' password='{}'".format(p))
except:
    print("I am unable to connect to the database")
cur = conn.cursor()

In [110]:
cur.execute('SELECT * FROM postgres LIMIT 2;')
for r in cur.fetchall():
   print(r)

InternalError: current transaction is aborted, commands ignored until end of transaction block

#### Using Pandas

In [111]:
p = getpass.getpass()
try:
    conn = psycopg2.connect("dbname='postgres' user='rsouza' host='localhost' password='{}'".format(p))
except:
    print("I am unable to connect to the database")

In [113]:
df_postgres = psql.read_sql('SELECT * FROM postgres LIMIT 5;', con=conn)
df_postgres.head()

DatabaseError: Execution failed on sql 'SELECT * FROM postgres LIMIT 5;': relation "postgres" does not exist
LINE 1: SELECT * FROM postgres LIMIT 5;
                      ^

### Acessing Mongo DB

http://api.mongodb.org/python/current/tutorial.html

In [132]:
from pymongo import MongoClient

In [133]:
client = MongoClient()
#client = MongoClient('localhost', 27017)
db = client.test_database #acessa ou cria o banco

## dropping a database via pymongo
#client.drop_database('test_database')

In [134]:
post = {"author": "Renato",
        "text": "My first blog post!",
        "tags": ["mongodb", "python", "pymongo"],
        "date": datetime.datetime.utcnow()}

In [135]:
posts = db.posts # cria a coleção
post_id = posts.insert_one(post) #insere dados
post_id

## drop a collection via pymongo
#client['test_database'].drop_collection('posts')

ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

In [ ]:
db.collection_names()

In [ ]:
posts.find_one()

In [ ]:
new_posts = [{"author": "Mike",
              "text": "Another post!",
              "tags": ["bulk", "insert"],
              "date": datetime.datetime(2009, 11, 12, 11, 14)},
             {"author": "Eliot",
              "title": "MongoDB is fun",
              "text": "and pretty easy too!",
              "date": datetime.datetime(2009, 11, 10, 10, 45)}]

In [ ]:
posts.insert_many(new_posts)

In [ ]:
posts.find_one({"author": "Mike"})

In [ ]:
#for post in posts.find({"author": "Mike"}):
for post in posts.find():
    print(post)

In [ ]:
posts.count()

#### Using Pandas

In [ ]:
example_pd = posts.find()
df_pandas =  pd.DataFrame(list(example_pd))
df_pandas

## Accessing Feeds RSS

http://www.feedparser.org/  
http://docs.python.org/library/re.html  
http://www.pythonware.com/library/pil/handbook/index.htm

In [ ]:
import feedparser

In [ ]:
#d = feedparser.parse('http://g1.globo.com/dynamo/rss2.xml')
d = feedparser.parse('http://rss.nytimes.com/services/xml/rss/nyt/InternationalHome.xml')

In [ ]:
print(d['feed']['title'])
print(d['feed']['link'])
print(d.feed.subtitle)
print(len(d['entries']))

In [ ]:
print(d['entries'][0]['title']) 
print(d.entries[0]['link'])

In [ ]:
print(d.headers)

In [ ]:
for post in d.entries:
    print(post.title + ": " + post.link + "\n")

## Acessando Twitter

https://github.com/bear/python-twitter  
Go to http://twitter.com/apps/new to create an app and get these items  
See https://dev.twitter.com/docs/auth/oauth for more information on Twitter's OAuth implementation  
https://dev.twitter.com/rest/reference/get/account/verify_credentials  
https://dev.twitter.com/oauth/overview/application-owner-access-tokens

In [ ]:
import twitter

In [ ]:
with open('/home/rsouza/Dropbox/Renato/ModMinDados/Git/notebooks/twitter_tokens.txt', 'r') as twitter_tokens:
    tokens = twitter_tokens.read().split(',')
consumer_key = tokens[0].strip()
consumer_secret = tokens[1].strip()
access_token = tokens[2].strip()
access_token_secret = tokens[3].strip()

Construct, sign, and open a twitter request using the hard-coded credentials above.

In [ ]:
api = twitter.Api(consumer_key=consumer_key, consumer_secret=consumer_secret, 
                  access_token_key=access_token, access_token_secret=access_token_secret)

In [ ]:
print(api.VerifyCredentials())

In [ ]:
users = api.GetFriends()
print([u.name for u in users])

In [ ]:
followers = api.GetFollowers()
print([u.screen_name for u in followers])

In [ ]:
mentions = api.GetMentions()
#mentions[0].text
print([m.text for m in mentions])

In [ ]:
statuses = api.GetUserTimeline(screen_name='TIME')
print([s.text for s in statuses])